import Foreword from "./foreword";
import Acknowledgements from "./acknowledgements";
import Epigraph from "./epigraph";
import Ancestry from "./ancestry";
import Aufhebung from "./aufhebung";
import Coalesce from "./coalesce";
import Ecology from "./ecology";
import Educate from "./educate";
import Enchant from "./enchant";
import Evolve from "./evolve";
import Ghost from "./ghost";
import Grave from "./grave";

const publication = {
  id: "tom",
  author: "Tom",
  authorFull: "Rena Tom",
  name: "Encyclopedia of Craft Studies (Abridged)",
  articles: [
    {
      id: "foreword",
      order: 1,
      title: "Foreword",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "new writing (student)",
        "introduction",
        "interdisciplinarity",
        "knowledge classification",
      ],
      citation: `Tom, Rena. "Foreword," in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/foreword",
      component: <Foreword />,
    },
    {
      id: "acknowledgements",
      order: 2,
      title: "Acknowledgements",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: ["community", "macr program", "support networks"],
      citation: `Tom, Rena. "Acknowledgments," in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/acknowledgments",
      component: <Acknowledgements />,
    },
    {
      id: "epigraph",
      order: 3,
      title: "Epigraph",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: ["reprint", "excerpt", "future", "renewal"],
      citation: `Tom, Rena. “Epigraph,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/epigraph ",
      component: <Epigraph />,
    },
    {
      id: "ancestry",
      order: 4,
      title: "Ancestry",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "reprint",
        "visual essay",
        "anthropology",
        "community",
        "heritage",
        "memory",
        "methodology",
      ],
      citation: `Tom, Rena. “Ancestry,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/ancestry ",
      component: <Ancestry />,
    },
    {
      id: "foreword",
      order: 5,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "aufhebung",
      order: 6,
      title: "Aufhebung",
      author: "Lucia Ilene Wallace",
      authorShort: "Wallace",
      tags: [
        "reprint",
        "excerpt",
        "absence",
        "ceramic",
        "destruction",
        "objectlessness",
        "renewal",
      ],
      citation: `Wallace, Lucia Ilene. “Aufhebung,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/aufhebung ",
      component: <Aufhebung />,
    },
    {
      id: "coalesce",
      order: 7,
      title: "Coalesce",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "new writing (student)",
        "visual essay",
        "community",
        "future",
        "support networks",
      ],
      citation: `Tom, Rena. “Coalesce,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/coalesce",
      component: <Coalesce />,
    },
    {
      id: "ecology",
      order: 8,
      title: "Ecology",
      author: "Anna Lowenhaupt Tsing",
      authorShort: "Tsing",
      tags: ["reprint", "excerpt", "death", "destruction", "ecology", "future"],
      citation: `Tsing, Anna Lowenhaupt. “Ecology,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/ecology",
      component: <Ecology />,
    },
    {
      id: "educate",
      order: 9,
      title: "Educate",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "new writing (student)",
        "visual essay",
        "community",
        "craft studies",
        "pedagogy",
        "support networks",
      ],
      citation: `Tom, Rena. “Educate,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/educate",
      component: <Educate />,
    },
    {
      id: "enchant",
      order: 10,
      title: "Enchant",
      author: "Karen Wilson Baptist",
      authorShort: "Baptist",
      tags: [
        "reprint",
        "excerpt",
        "absence",
        "memory",
        "philosophy",
        "transcience",
      ],
      citation: `Baptist, Karen Wilson. “Enchant,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/enchant",
      component: <Enchant />,
    },
    {
      id: "evolve",
      order: 11,
      title: "Evolve",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "new writing (student)",
        "visual essay",
        "absence",
        "curation",
        "knowledge classification",
      ],
      citation: `Tom, Rena. “Evolve,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/evolve",
      component: <Evolve />,
    },
    {
      id: "ghost",
      order: 12,
      title: "Ghost",
      author: "Sara Clugage",
      authorShort: "Clugage",
      tags: [
        "new writing (faculty)",
        "essay",
        "absence",
        "craft studies",
        "future",
        "materiality",
      ],
      citation: `Clugage, Sara. “Ghost,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/ghost ",
      component: <Ghost />,
    },
    {
      id: "grave",
      order: 13,
      title: "Grave",
      author: "Jarrett M. Drake",
      authorShort: "Drake",
      tags: ["reprint", "excerpt", "archives", "community", "death", "future"],
      citation: `Drake, Jarrett M. “Grave,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/grave ",
      component: <Grave />,
    },
    {
      id: "foreword",
      order: 14,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 15,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 16,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 17,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 18,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 19,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 20,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 21,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 22,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 23,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 24,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 25,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 26,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 27,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 28,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 29,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 30,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 31,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 32,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 33,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 34,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 35,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
  ],
  accent: "#e5bd01",
};

export default publication;
