import Foreword from "./foreword";
import Acknowledgements from "./acknowledgements";
import Epigraph from "./epigraph";
import Ancestry from "./ancestry";
import Aufhebung from "./aufhebung";
import Coalesce from "./coalesce";
import Ecology from "./ecology";
import Educate from "./educate";
import Enchant from "./enchant";
import Evolve from "./evolve";
import Ghost from "./ghost";
import Grave from "./grave";
import Legacy from "./legacy";
import Lifespan from "./lifespan";
import Liminal from "./liminal";
import Magic from "./magic";
import Map from "./map";
import Memorial from "./memorial";
import Offering from "./offering";
import Palimpsest from "./palimpsest";
import Portrait from "./portrait";
import Predict from "./predict";
import Publication from "./publication";
import Queer from "./queer";
import Reframe from "./reframe";
import Renewal from "./renewal";
import Repair from "./repair";
import Resolve from "./resolve";
import Souvenir from "./souvenir";
import Speculate from "./speculate";

const publication = {
  id: "tom",
  author: "Tom",
  authorFull: "Rena Tom",
  name: "Encyclopedia of Craft Studies (Abridged)",
  articles: [
    {
      id: "foreword",
      order: 1,
      title: "Foreword",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "new writing (student)",
        "introduction",
        "interdisciplinarity",
        "knowledge classification",
      ],
      citation: `Tom, Rena. "Foreword," in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/foreword",
      component: <Foreword />,
    },
    {
      id: "acknowledgements",
      order: 2,
      title: "Acknowledgements",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: ["community", "macr program", "support networks"],
      citation: `Tom, Rena. "Acknowledgments," in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/acknowledgments",
      component: <Acknowledgements />,
    },
    {
      id: "epigraph",
      order: 3,
      title: "Epigraph",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: ["reprint", "excerpt", "future", "renewal"],
      citation: `Tom, Rena. “Epigraph,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/epigraph ",
      component: <Epigraph />,
    },
    {
      id: "ancestry",
      order: 4,
      title: "Ancestry",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "reprint",
        "visual essay",
        "anthropology",
        "community",
        "heritage",
        "memory",
        "methodology",
      ],
      citation: `Tom, Rena. “Ancestry,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/ancestry ",
      component: <Ancestry />,
    },
    {
      id: "archive",
      order: 5,
      title: "Archive",
      author: "Namita Gupta Wiggers",
      authorShort: "Gupta Wiggers",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "aufhebung",
      order: 6,
      title: "Aufhebung",
      author: "Lucia Ilene Wallace",
      authorShort: "Wallace",
      tags: [
        "reprint",
        "excerpt",
        "absence",
        "ceramic",
        "destruction",
        "objectlessness",
        "renewal",
      ],
      citation: `Wallace, Lucia Ilene. “Aufhebung,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/aufhebung ",
      component: <Aufhebung />,
    },
    {
      id: "coalesce",
      order: 7,
      title: "Coalesce",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "new writing (student)",
        "visual essay",
        "community",
        "future",
        "support networks",
      ],
      citation: `Tom, Rena. “Coalesce,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/coalesce",
      component: <Coalesce />,
    },
    {
      id: "ecology",
      order: 8,
      title: "Ecology",
      author: "Anna Lowenhaupt Tsing",
      authorShort: "Tsing",
      tags: ["reprint", "excerpt", "death", "destruction", "ecology", "future"],
      citation: `Tsing, Anna Lowenhaupt. “Ecology,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/ecology",
      component: <Ecology />,
    },
    {
      id: "educate",
      order: 9,
      title: "Educate",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "new writing (student)",
        "visual essay",
        "community",
        "craft studies",
        "pedagogy",
        "support networks",
      ],
      citation: `Tom, Rena. “Educate,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/educate",
      component: <Educate />,
    },
    {
      id: "enchant",
      order: 10,
      title: "Enchant",
      author: "Karen Wilson Baptist",
      authorShort: "Baptist",
      tags: [
        "reprint",
        "excerpt",
        "absence",
        "memory",
        "philosophy",
        "transcience",
      ],
      citation: `Baptist, Karen Wilson. “Enchant,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/enchant",
      component: <Enchant />,
    },
    {
      id: "evolve",
      order: 11,
      title: "Evolve",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "new writing (student)",
        "visual essay",
        "absence",
        "curation",
        "knowledge classification",
      ],
      citation: `Tom, Rena. “Evolve,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/evolve",
      component: <Evolve />,
    },
    {
      id: "ghost",
      order: 12,
      title: "Ghost",
      author: "Sara Clugage",
      authorShort: "Clugage",
      tags: [
        "new writing (faculty)",
        "essay",
        "absence",
        "craft studies",
        "future",
        "materiality",
      ],
      citation: `Clugage, Sara. “Ghost,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/ghost ",
      component: <Ghost />,
    },
    {
      id: "grave",
      order: 13,
      title: "Grave",
      author: "Jarrett M. Drake",
      authorShort: "Drake",
      tags: ["reprint", "excerpt", "archives", "community", "death", "future"],
      citation: `Drake, Jarrett M. “Grave,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/grave ",
      component: <Grave />,
    },
    {
      id: "legacy",
      order: 14,
      title: "Legacy",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "coursework",
        "visual essay",
        "absence",
        "craft practices",
        "heritage",
        "mapping",
      ],
      citation: `Tom, Rena. “Legacy,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/legacy",
      component: <Legacy />,
    },
    {
      id: "lifespan",
      order: 15,
      title: "Lifespan",
      author: "Paul Benzon and Future Library",
      authorShort: "Benzon & Future Library",
      tags: [
        "reprint",
        "excerpt",
        "ecology",
        "future",
        "heritage",
        "self-publishing",
        "writing",
      ],
      citation: `Benzon, Paul and Future Library. “Lifespan,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/lifespan",
      component: <Lifespan />,
    },
    {
      id: "liminal",
      order: 16,
      title: "Liminal",
      author: "Alex Singh",
      authorShort: "Singh",
      tags: [
        "reprint",
        "excerpt",
        "interdisciplinarity",
        "philosophy",
        "weaving",
      ],
      citation: `Singh, Alex. “Liminal,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/liminal ",
      component: <Liminal />,
    },
    {
      id: "magic",
      order: 17,
      title: "Magic",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "new writing (student)",
        "visual essay",
        "absence",
        "aesthetics",
        "embodied knowledge",
        "philosophy",
        "transcience",
      ],
      citation: `Tom, Rena. “Magic,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/magic",
      component: <Magic />,
    },
    {
      id: "map",
      order: 18,
      title: "Map",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "coursework",
        "visual essay",
        "community",
        "craft studies",
        "knowledge classification",
        "mapping",
        "resistance",
      ],
      citation: `Tom, Rena. “Map,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/map",
      component: <Map />,
    },
    {
      id: "memorial",
      order: 19,
      title: "Memorial",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "new writing (student)",
        "visual essay",
        "ecology",
        "memory",
        "transcience",
      ],
      citation: `Tom, Rena. “Memorial,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/memorial",
      component: <Memorial />,
    },
    {
      id: "offering",
      order: 20,
      title: "Offering",
      author: "Phoebe Cheng",
      authorShort: "Cheng",
      tags: [
        "reprint",
        "essay",
        "aesthetics",
        "anthropology",
        "community",
        "heritage",
        "transcience",
      ],
      citation: `Cheng, Phoebe. “Offering,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/offering",
      component: <Offering />,
    },
    {
      id: "palimpsest",
      order: 21,
      title: "Palimpsest",
      author: "Indira Allegra",
      authorShort: "Allegra",
      tags: [
        "new writing (contributor)",
        "essay",
        "labor",
        "transcience",
        "weaving",
      ],
      citation: `Allegra, Indira. “Palimpsest,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/palimpsest",
      component: <Palimpsest />,
    },
    {
      id: "portrait",
      order: 22,
      title: "Portrait",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "new writing (student)",
        "visual essay",
        "community",
        "support networks",
      ],
      citation: `Tom, Rena. “Portrait,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/portrait",
      component: <Portrait />,
    },
    {
      id: "predict",
      order: 23,
      title: "Predict",
      author: "Andres Payan Estrada",
      authorShort: "Estrada",
      tags: [
        "new writing (faculty)",
        "visual essay",
        "aesthetics",
        "craft practices",
        "future",
      ],
      citation: `Estrada, Andres Payan. “Predict,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/predict",
      component: <Predict />,
    },
    {
      id: "publication",
      order: 24,
      title: "Publication",
      author: "Ben Lignel",
      authorShort: "Lignel",
      tags: [
        "new writing (faculty)",
        "essay",
        "community",
        "future",
        "philosophy",
      ],
      citation: `Lignel, Ben. “The Letter R,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/publication ",
      component: <Publication />,
    },
    {
      id: "queer",
      order: 25,
      title: "Queer",
      author: "matt lambert",
      authorShort: "lambert",
      tags: [
        "new writing (alumni)",
        "essay",
        "community",
        "future",
        "memory",
        "queer life",
      ],
      citation: `lambert, matt. “Queer Companion,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/queer",
      component: <Queer />,
    },
    {
      id: "reframe",
      order: 26,
      title: "Reframe",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: ["coursework", "essay", "aesthetics", "ethnography"],
      citation: `Tom, Rena. “Reframe,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/reframe",
      component: <Reframe />,
    },
    {
      id: "renewal",
      order: 27,
      title: "Renewal",
      author: "Brian Potter",
      authorShort: "Potter",
      tags: [
        "reprint",
        "essay",
        "craft studies",
        "destruction",
        "heritage",
        "repair",
      ],
      citation: `Potter, Brian. “Renewal,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/renewal",
      component: <Renewal />,
    },
    {
      id: "repair",
      order: 28,
      title: "Repair",
      author: "Miriam Devlin",
      authorShort: "Devlin",
      tags: [
        "new writing (student)",
        "essay",
        "aesthetics",
        "future",
        "heritage",
        "renewal",
        "repair",
      ],
      citation: `Devlin, Miriam. “Repair,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/repair ",
      component: <Repair />,
    },
    {
      id: "resolve",
      order: 29,
      title: "Resolve",
      author: "Jill DiMassimo",
      authorShort: "DiMassimo",
      tags: [
        "new writing (student)",
        "essay",
        "absence",
        "aesthetics",
        "heritage",
      ],
      citation: `DiMassimo, Jill. “Resolve,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/resolve",
      component: <Resolve />,
    },
    {
      id: "souvenir",
      order: 30,
      title: "Souvenir",
      author: "Rena Tom",
      authorShort: "Tom",
      tags: [
        "new writing (student)",
        "essay",
        "absence",
        "community",
        "future",
        "memory",
      ],
      citation: `Tom, Rena. “Souvenir,” in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/souvenir",
      component: <Souvenir />,
    },
    {
      id: "speculate",
      order: 31,
      title: "Speculate",
      author: "Tom Martin",
      authorShort: "Martin",
      tags: [
        "new writing (faculty)",
        "essay",
        "absence",
        "future",
        "phenomenology",
        "philosophy",
      ],
      citation: `Martin, Tom. “Speculate”, in Encyclopedia of Craft Studies (Abridged) edited by Rena Tom. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-8-7 `,
      url: "https://www.theMACRPapers/tom/speculate",
      component: <Speculate />,
    },
    {
      id: "foreword",
      order: 32,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 33,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 34,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "foreword",
      order: 35,
      title: "",
      author: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
  ],
  accent: "#e5bd01",
};

export default publication;
