import Foreword from "./foreword";
import Hall from "./hall";
import Joyce from "./joyce";

const publication = {
  id: "hand",
  author: "Hand",
  authorFull: "Jennifer Hand",
  name: "The Space Between Us - Writing Across Difference in the Crafts",
  articles: [
    {
      id: "foreword",
      order: 1,
      title: "Foreword",
      author: "Jennifer Hand",
      authorShort: "Hand",
      tags: [
        "new writing",
        "introduction",
        "bias",
        "methodology",
        "self-knowledge",
        "writing",
      ],
      citation: `Hand, Jennifer. “Foreword,” The Space Between Us: Writing Across Difference in the Crafts, edited by Jennifer Hand. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-5-6  `,
      url: "https://www.theMACRPapers/hand/foreword",
      component: <Foreword />,
    },
    {
      id: "hall",
      order: 2,
      title: "Minimal Selves",
      author: "Stuart Hall",
      authorShort: "Hall",
      tags: [
        "reprint",
        "essay",
        "bias",
        "black history",
        "diaspora",
        "identity",
        "self-knowledge",
      ],
      citation: `Hand, Jennifer, “Introduction: Stuart Hall,” The Space Between Us: Writing Across Difference in the Crafts, edited by Jennifer Hand. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-5-6  `,
      url: "https://www.theMACRPapers/hand/hall",
      component: <Hall />,
    },
    {
      id: "joyce",
      order: 3,
      title: "Joyce Scott: Hard Truth in Beauty",
      author: "Jennifer Hand",
      authorShort: "Hand",
      tags: [
        "reprint",
        "interview",
        "black craftspeople",
        "craft practices",
        "criticism",
        "curation",
        "social justice",
      ],
      citation: `Hand, Jennifer, “Joyce Scott: Hard Truth in Beauty,” The Space Between Us: Writing Across Difference in the Crafts, edited by Jennifer Hand. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-5-6  `,
      url: "https://www.theMACRPapers/hand/joyce",
      component: <Joyce />,
    },
    {
      id: "ahmed",
      order: 4,
      title: "",
      author: "",
      authorShort: "Ahmed",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "josselson",
      order: 5,
      title: "",
      author: "",
      authorShort: "Josselson",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "taylor",
      order: 6,
      title: "",
      author: "",
      authorShort: "Taylor",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "leeandhand",
      order: 7,
      title: "",
      author: "",
      authorShort: "Lee & Hand",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "vowel",
      order: 8,
      title: "",
      author: "",
      authorShort: "Vowel",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
  ],
  accent: "#0baeef",
};

export default publication;
