import Adamson from "./adamson";
import Devlin from "./devlin";
import EditorsNote from "./editorsnote";
import Kuo from "./kuo";
import WallKimmerer from "./wallkimmerer";

const publication = {
  id: "devlin",
  author: "Devlin",
  authorFull: "Miriam Devlin",
  name: "Craft Practiced, a reader",
  articles: [
    {
      id: "editorsletter",
      order: 1,
      title: "Editor's Letter",
      author: "Miriam Devlin",
      authorShort: "Devlin",
      tags: [
        "new writing",
        "introduction",
        "conversation",
        "craft studies",
        "embodied knowledge",
        "somatics",
        "translation",
      ],
      citation: `Devlin, Miriam. “Editor’s Letter,” Craft Practiced, a reader, edited by Miriam Devlin. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-7-0  `,
      url: "https://www.theMACRPapers.com/devlin/editorsletter",
      component: <EditorsNote />,
    },
    {
      id: "wallkimmerer",
      order: 2,
      title: "Wisgaak Gokpenagen: A Black Ash Basket",
      author: "Robin Wall Kimmerer",
      authorShort: "Kimmerer",
      tags: [
        "reprint",
        "chapter",
        "basket weaving",
        "craft practices",
        "ecology",
        "indigenous knowledge",
      ],
      citation: `Devlin, Miriam. “Introduction: Robin Wall Kimmerer,” Craft Practiced, a reader, edited by Miriam Devlin. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-7-0  `,
      url: "https://www.theMACRPapers.com/devlin/wallkimmerer",
      component: <WallKimmerer />,
    },
    {
      id: "adamson",
      order: 3,
      title: "Material Intelligence",
      author: "Glenn Adamson",
      authorShort: "Adamson",
      tags: ["reprint", "essay", "agency", "anthropology", "craft studies"],
      citation: `Devlin, Miriam. “Introduction: Glenn Adamson,” Craft Practiced, a reader, edited by Miriam Devlin. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-7-0  `,
      url: "https://www.theMACRPapers.com/devlin/adamson",
      component: <Adamson />,
    },
    {
      id: "devlin",
      order: 4,
      title: "On Frames",
      author: "Trieste Devlin",
      authorShort: "Devlin",
      tags: [
        "new writing",
        "commentary",
        "agency",
        "conversation",
        "craft practices",
        "dye",
        "translation",
      ],
      citation: `Devlin, Trieste. “On Frames,” Craft Practiced, a reader, edited by Miriam Devlin. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-7-0  `,
      url: "https://www.theMACRPapers.com/devlin/devlin",
      component: <Devlin />,
    },
    {
      id: "kuo",
      order: 5,
      title: "Swimming Ethnography",
      author: "Phoebe Kuo",
      authorShort: "Kuo",
      tags: [
        "coursework",
        "essay",
        "ethnography",
        "movement",
        "phenomenology",
        "poetry",
      ],
      citation: `Kuo, Phoebe. “Swimming Ethnography,” Craft Practiced, a reader, edited by Miriam Devlin. The MACR Papers, Swannanoa, NC: MA in Critical Craft Studies, Warren Wilson College, 2023. Copyright remains with the author. ISBN 978-1-7351592-7-0  `,
      url: "https://www.theMACRPapers.com/devlin/kuo",
      component: <Kuo />,
    },
    {
      id: "",
      order: 1,
      title: "",
      author: "",
      authorShort: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "",
      order: 1,
      title: "",
      author: "",
      authorShort: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "",
      order: 1,
      title: "",
      author: "",
      authorShort: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "",
      order: 1,
      title: "",
      author: "",
      authorShort: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
    {
      id: "",
      order: 1,
      title: "",
      author: "",
      authorShort: "",
      tags: [],
      citation: ``,
      url: "",
      component: "",
    },
  ],
  accent: "#cf2228",
};

export default publication;
